# Generated by Django 6.0.2 on 2026-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0015_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
