# Generated by Django 6.0.2 on 2026-06-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0017_remove_category_name_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
