# Generated by Django 6.0.2 on 2026-06-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0017_product_category_fk'),
        ('sellerapp', '0018_alter_category_options'),
    ]

    operations = [
    ]
